@listaTarefas_api_HostAddress = http://localhost:5065

GET {{listaTarefas_api_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{listaTarefas_api_HostAddress}}/api/Tarefa
Accept: application/json

###
GET {{listaTarefas_api_HostAddress}}/api/Tarefa/5
Accept: application/json

###

POST {{listaTarefas_api_HostAddress}}/api/Tarefa
Content-Type: application/json

{
    "id" : 7,
    "Descricao": "Teste 33",
    "Concluida": false
}

###

PUT {{listaTarefas_api_HostAddress}}/api/Tarefa/5
Content-Type: application/json

{
    "Id": 5,
    "Descricao": "Teste 10 - alterado denovo",
    "Concluida": false
}

###

DELETE {{listaTarefas_api_HostAddress}}/api/Tarefa/5
Accept: application/json
###