@listaTarefas_api_HostAddress = http://localhost:5065

GET {{listaTarefas_api_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{listaTarefas_api_HostAddress}}/api/Tarefa
Accept: application/json

###
GET {{listaTarefas_api_HostAddress}}/api/Tarefa/3
Accept: application/json

###

POST {{listaTarefas_api_HostAddress}}/api/Tarefa
Content-Type: application/json

{
    "Descricao": "Teste 8",
    "Concluida": false
}

###

PUT {{listaTarefas_api_HostAddress}}/api/Tarefa/5
Content-Type: application/json

{
    "Id": 5,
    "Descricao": "Teste 9 - alterado denovo",
    "Concluida": false
}

###