@listaTarefas_api_HostAddress = http://localhost:5065

GET {{listaTarefas_api_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{listaTarefas_api_HostAddress}}/api/Tarefa
Accept: application/json

###
GET {{listaTarefas_api_HostAddress}}/api/Tarefa/8
Accept: application/json

###

POST {{listaTarefas_api_HostAddress}}/api/Tarefa
Content-Type: application/json

{
    "id" : 8,
    "Descricao": "fazer meu pão com ovo",
    "Concluida": false
}

###

PUT {{listaTarefas_api_HostAddress}}/api/Tarefa/8
Content-Type: application/json

{
    "Id": 8,
    "Descricao": "fazer meu pão com ovo",
    "Concluida": true
}

###

DELETE {{listaTarefas_api_HostAddress}}/api/Tarefa/5
Accept: application/json
###